import express from 'express';
import cookieParser from 'cookie-parser';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { config } from './config.js';
import { HttpCspClient, type CspClient } from './csp/client.js';
import { MockCspClient } from './csp/mock.js';
import { createApiRouter } from './routes.js';
import { SessionStore } from './sessions.js';

if (config.insecureTls && config.cspUrl.startsWith('https:')) {
  // CSP nodes usually run a self-signed certificate generated by gen-keystore.
  process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
}

const csp: CspClient = config.mock ? new MockCspClient() : new HttpCspClient(config.cspUrl);
const sessions = new SessionStore(config.sessionTtlMs);

const app = express();
app.disable('x-powered-by');
app.set('trust proxy', true);

app.use(cookieParser());
app.use(express.json({ limit: '2mb' }));
app.use(express.text({ type: ['text/xml', 'application/xml', 'text/plain'], limit: '8mb' }));

app.get('/healthz', (_req, res) => {
  res.json({ ok: true, backend: csp.kind, target: csp.target });
});

app.use('/api', createApiRouter(csp, sessions, false));

// Serve the built SPA when it exists (single-artifact deployment).
const webRoot = config.webRoot;
if (existsSync(join(webRoot, 'index.html'))) {
  app.use(express.static(webRoot, { index: false, maxAge: '1h' }));
  app.get('*', (_req, res) => res.sendFile(join(webRoot, 'index.html')));
} else {
  app.get('/', (_req, res) => {
    res
      .status(200)
      .type('text/plain')
      .send(
        [
          'CSP panel API is running.',
          `backend: ${csp.kind} (${csp.target})`,
          '',
          'The frontend has not been built yet. Run `npm run build` in panel/,',
          'or use `npm run dev` and open the Vite dev server instead.',
        ].join('\n'),
      );
  });
}

app.listen(config.port, config.host, () => {
  console.log(`[csp-panel] api listening on http://${config.host}:${config.port}`);
  console.log(`[csp-panel] backend: ${csp.kind} -> ${csp.target}`);
  if (csp.kind === 'mock') console.log('[csp-panel] mock mode: log in with any user/password (use "admin" for admin rights)');
});
